<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
    <!--	<base href="http://localhost/mvc/" />-->
    <title>Phalcon PHP Framework</title>
    <link rel="stylesheet" href="<?= __CSS_URL; ?>style.css">
    <link rel="stylesheet" href="<?= __CSS_URL; ?>paging.css">
</head>

<body>

<div id="container">

    <div id="top">
        <h1>Simple MVC Framework</h1>
    </div>

    <div id="leftnav">
        <ul>
            <li><a href="/z-cms/">Home</a></li>
            <li><a href="/z-cms/site/home/render">Render Action</a></li>
            <li><a href="/z-cms/site/index/captcha">Captcha Demo</a></li>
            <li><a href="/z-cms/paging/page/paginator">Paging</a></li>
            <li><a href="/z-cms/database/model">Normal Database</a></li>
            <li><a href="/z-cms/pdo-database/pdo-model">PDO Model Database</a></li>
            <li><a href="/z-cms/active-record/active-record">Active Record Database</a></li>
            <li><a href="/z-cms/site/home/ckeditor">CKEditor</a></li>
            <li><a href="/z-cms/page-module/content/load-data-test">Page Module SEO Test</a></li>
            <li><a href="/z-cms/links/content/load-data-test/nhung-bi-mat-lon-nhat-ve-phat-xit-duc-duoc-phat-hien-3271796.html">Router Links</a></li>
        </ul>
    </div>

    <div id="content">
        <?php echo $this->getContent(); ?>
    </div>

    <div id="footer">
        Powered By <a href="mailto:buivantienduc@yahoo.com">Bui Van Tien Duc</a>
    </div>

</div>

</body>
</html>
